### ISSUE TITLE
Client connect state

### ISSUE THREAD

**Issue by ddosoff** [zheludkovm/RustyTarantool#1]
Hi, how I can detect and react to the client connection error?
How I can wait until client is connected?

**Comment by zheludkovm** [comment]
Currently if you loose connection - you just receive timeout error by all futures returned by calls
(to enable this - set timeout to client)
Client state don't exposed by API.

if you interested in this feature - i can add access to current client state 
and may be add special method wait_connection() which return future completed after connection success

**Comment by ddosoff** [comment]
Will be awesome.

I tried to connect closed port and just got panic. Please check it.

**Comment by zheludkovm** [comment]
Submit new version 1.2 to git and crates.io -
- add method get_status() - check current status of connection
- add method ping() - send ping command to tarantool

**Comment by zheludkovm** [comment]
add stream to track status change 

tarantool_ref.subscribe_to_notify_stream().for_each(|status| {
                println!("status change to = {:?}", status);
                 Ok(())
})
