### ISSUE TITLE
Why there is replace_raw() command?

### ISSUE THREAD

**Issue by akhilman** [zheludkovm/RustyTarantool#10]
Is [`replace_raw()`](https://github.com/zheludkovm/RustyTarantool/commit/dfb50c5650d0a8c41a211ece262b3a042c0f858c) command a hack? Why such unsafe command is here?

**Comment by zheludkovm** [comment]
This is lowlevel method for hackers who want manually code msg pack.
Guys using RustyTarantool in production asks me to add it
