### ISSUE TITLE
Drop actix or make it optional.

### ISSUE THREAD

**Issue by akhilman** [zheludkovm/RustyTarantool#3]
Actix is [moving away from tokio runtime](https://github.com/actix/actix/issues/298#issuecomment-558875341). To port RustyTarantool to tokio-0.2 and futures-0.3 #2  we should do something with actix example.

**Comment by zheludkovm** [comment]
Current actix is compatible with RustyTarantool
https://github.com/zheludkovm/RustyTarantool/blob/master/examples/actix-tarantool-proxy.rs
