### ISSUE TITLE
Use new call protocol.

### ISSUE THREAD

**Issue by akhilman** [zheludkovm/RustyTarantool#8]
Is there a reason why we still use old call API [here](https://github.com/zheludkovm/RustyTarantool/blob/8d8beae82885b1f04c0dcf2a74508d2519fd2764/src/tarantool/packets.rs#L128)?

From [tarantool documentation](https://www.tarantool.io/en/doc/2.2/dev_guide/internals/box_protocol/#box-protocol-iproto-protocol):
> CALL_16: CODE - 0x06 Call a stored function, returning an array of tuples. **This is deprecated; CALL (0x0a) is recommended instead**.

**Comment by zheludkovm** [comment]
Ok, i will add new method

**Comment by zheludkovm** [comment]
switched call to 0x0a
version 0.2.3
