### ISSUE TITLE
Can not find any defined constants for iterator types.

### ISSUE THREAD

**Issue by akhilman** [zheludkovm/RustyTarantool#9]
I believe iterator types (`iproto_iter` used in select command) should be defined as enum. But I could not find any definition in source code.

**Comment by akhilman** [comment]
Here is right values: https://github.com/tarantool/tarantool/blob/952d8d1d4ffe81a0be4d7901f063f6c5059d71f5/src/box/iterator_type.h#L62

**Comment by zheludkovm** [comment]
Ok, forget about it
i will add constants, thank you

**Comment by akhilman** [comment]
I am working on porting the code to the futures-0.3. After that I plan to rewrite the API as described [here](https://github.com/akhilman/RustyTarantool/issues/3). Will be great if these changes will be merged to upstream.

**Comment by zheludkovm** [comment]
Add iterator constants  in 0.2.2
